branch-defaults:
  default:
    environment: development-env
environment-defaults:
  development-env:
    branch: null
    repository: null
global:
  application_name: Sorting Visualiser
  default_ec2_keyname: aws-eb
  default_platform: Docker 17.06.2-ce
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
